services:
  app:
    build: .
    working_dir: /home/app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app
      - app_node_modules:/home/app/node_modules
    environment:
      - UNOPTIMIZED=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - PATH=/home/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    tty: true
    stdin_open: true

volumes:
  app_node_modules:
